import { Router } from "express";
import Database from "@replit/database";
import { logger } from "../lib/logger.js";
import {
  createBrief,
  getBrief,
  updateBrief,
  listBriefs,
} from "../lib/briefHistory.js";
import { getSettings } from "../lib/settings.js";

type DbResult<T> = { ok: true; value: T } | { ok: false; error: unknown };

const _db = new Database();

async function dbGet<T>(key: string): Promise<T | null> {
  const result = await (_db as unknown as { get(k: string): Promise<DbResult<T | null>> }).get(key);
  if (!result.ok) {
    const statusCode = ((result as { ok: false; error: unknown }).error as { statusCode?: number })?.statusCode;
    if (statusCode === 404) return null;
    throw new Error(`DB error (get:${key})`);
  }
  return (result as { ok: true; value: T | null }).value;
}

async function dbList(prefix: string): Promise<string[]> {
  const result = await (_db as unknown as { list(p: string): Promise<DbResult<string[]>> }).list(prefix);
  if (!result.ok) return [];
  return (result as { ok: true; value: string[] }).value ?? [];
}

interface TriggeredAlert {
  nctId: string;
  detectedAt: string;
  module: string;
  severity: "critical" | "high" | "medium" | "low";
  headline: string;
  detail: string;
}

async function listKillChainAlerts(): Promise<TriggeredAlert[]> {
  const keys = await dbList("trial:alerts:");
  const all: TriggeredAlert[] = [];
  for (const key of keys) {
    const alerts = await dbGet<TriggeredAlert[]>(key);
    if (Array.isArray(alerts)) all.push(...alerts);
  }
  return all.sort((a, b) => new Date(b.detectedAt).getTime() - new Date(a.detectedAt).getTime());
}

const router = Router();

class ApiError extends Error {
  constructor(
    public readonly httpStatus: number,
    message: string,
  ) {
    super(message);
    this.name = "ApiError";
  }
}

function handleError(
  err: unknown,
  res: Parameters<Parameters<typeof router.get>[1]>[1],
): void {
  if (err instanceof ApiError) {
    res.status(err.httpStatus).json({ error: err.message });
  } else {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error({ err }, "Briefs route error");
    res.status(500).json({ error: msg });
  }
}

function buildBriefDocContent(alerts: TriggeredAlert[]): string {
  const now = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  const severityOrder: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };
  const sorted = [...alerts].sort(
    (a, b) => (severityOrder[a.severity] ?? 9) - (severityOrder[b.severity] ?? 9),
  );

  const alertSections = sorted
    .map(
      (a, i) => `
${i + 1}. [${a.severity.toUpperCase()}] ${a.nctId} — ${a.module}
   Detected: ${new Date(a.detectedAt).toLocaleString("en-US")}

   ${a.headline}

   ${a.detail}
`,
    )
    .join("\n" + "—".repeat(50) + "\n");

  return `COMPETITOR INTELLIGENCE BRIEFING
Date: ${now}
Active Alerts: ${alerts.length}

${"=".repeat(60)}

${alertSections}

${"=".repeat(60)}

RECOMMENDED NEXT STEPS
[PI to complete — Review each alert above and advise on implications for our trial strategy and recruitment targets.]

---
Generated by Clinical Trials Co-Pilot — Competitor Intelligence`;
}


router.get("/briefs", async (_req, res): Promise<void> => {
  try {
    const briefs = await listBriefs();
    res.json(briefs);
  } catch (err) {
    handleError(err, res);
  }
});

router.post(["/briefs", "/internal/draft-memo"], async (_req, res): Promise<void> => {
  try {
    const activeAlerts = await listKillChainAlerts();

    if (activeAlerts.length === 0) {
      throw new ApiError(
        409,
        "No active alerts to brief on. Use Refresh Swarm to scan competitor trials first.",
      );
    }

    const content = buildBriefDocContent(activeAlerts);
    const docTitle = `Competitor Intelligence Brief — ${new Date().toLocaleDateString("en-US")}`;

    const { ReplitConnectors } = await import("@replit/connectors-sdk");
    const connectors = new ReplitConnectors();

    const createRes = (await connectors.proxy(
      "google-drive",
      "/drive/v3/files",
      {
        method: "POST",
        body: JSON.stringify({
          name: docTitle,
          mimeType: "application/vnd.google-apps.document",
        }),
        headers: { "Content-Type": "application/json" },
      },
    )) as unknown as Response;

    if (!createRes.ok) {
      const text = await (createRes as Response).text();
      throw new ApiError(503, `Failed to create Google Doc: ${text.slice(0, 300)}`);
    }

    const created = (await (createRes as Response).json()) as {
      id?: string;
    };
    if (!created.id)
      throw new ApiError(503, "Drive API returned no file ID");

    const docId = created.id;

    try {
      const { getGoogleOAuth2Client } = await import(
        "../lib/googleOAuthClient.js"
      );
      const { google } = await import("googleapis");
      const auth = await getGoogleOAuth2Client("google-drive");
      const docs = google.docs({ version: "v1", auth });

      await docs.documents.batchUpdate({
        documentId: docId,
        requestBody: {
          requests: [
            {
              insertText: {
                location: { index: 1 },
                text: content,
              },
            },
          ],
        },
      });
    } catch (writeErr) {
      logger.error(
        { writeErr, docId },
        "Failed to write content to brief doc — doc created but empty",
      );
      throw new ApiError(
        503,
        `Document created but content could not be written: ${writeErr instanceof Error ? writeErr.message : String(writeErr)}`,
      );
    }

    const docUrl = `https://docs.google.com/document/d/${docId}/edit`;

    const brief = await createBrief({
      docUrl,
      docId,
      alertCount: activeAlerts.length,
      alertIds: activeAlerts.map((a) => `${a.nctId}:${a.module}`),
    });

    logger.info({ briefId: brief.id, alertCount: activeAlerts.length }, "Intelligence brief created");
    res.status(201).json(brief);
  } catch (err) {
    handleError(err, res);
  }
});

router.post("/briefs/:id/send-to-pi", async (req, res): Promise<void> => {
  try {
    const { id } = req.params;
    const brief = await getBrief(id);
    if (!brief) throw new ApiError(404, "Brief not found");
    if (brief.status !== "Draft")
      throw new ApiError(409, `Brief is already in ${brief.status} status`);

    const settings = await getSettings();

    const { getGmailClient } = await import("../lib/gmailClient.js");
    const gmail = await getGmailClient();

    const subject = `[Action Required] Competitor Intelligence Brief — ${new Date(brief.generatedAt).toLocaleDateString("en-US")}`;
    const body = [
      `<p>A new competitor intelligence briefing has been prepared for your review.</p>`,
      `<p>This brief covers <strong>${brief.alertCount} active alert${brief.alertCount !== 1 ? "s" : ""}</strong> detected from monitored competitor trials on ClinicalTrials.gov.</p>`,
      `<p><a href="${brief.docUrl}" style="font-size:16px;font-weight:bold;">Open Intelligence Brief →</a></p>`,
      `<p style="color:#888;font-size:12px;">Please review and advise on any implications for our trial strategy. Reply to confirm receipt.</p>`,
      `<p style="color:#888;font-size:12px;">Generated by Clinical Trials Co-Pilot — Competitor Intelligence</p>`,
    ].join("\n");

    const rawMessage = [
      `From: me`,
      `To: ${settings.piEmail}`,
      `Subject: ${subject}`,
      `MIME-Version: 1.0`,
      `Content-Type: text/html; charset=utf-8`,
      ``,
      body,
    ].join("\r\n");

    const encoded = Buffer.from(rawMessage).toString("base64url");
    await gmail.users.messages.send({
      userId: "me",
      requestBody: { raw: encoded },
    });

    const updated = await updateBrief(id, {
      status: "PI Review",
      sentToPiAt: new Date().toISOString(),
    });

    res.json(updated);
  } catch (err) {
    handleError(err, res);
  }
});

router.post("/briefs/:id/mark-approved", async (req, res): Promise<void> => {
  try {
    const { id } = req.params;
    const brief = await getBrief(id);
    if (!brief) throw new ApiError(404, "Brief not found");
    if (brief.status !== "PI Review")
      throw new ApiError(409, `Brief must be in PI Review to approve`);

    const updated = await updateBrief(id, {
      status: "Approved",
      approvedAt: new Date().toISOString(),
    });

    res.json(updated);
  } catch (err) {
    handleError(err, res);
  }
});

router.post("/briefs/:id/mark-final", async (req, res): Promise<void> => {
  try {
    const { id } = req.params;
    const brief = await getBrief(id);
    if (!brief) throw new ApiError(404, "Brief not found");
    if (brief.status !== "Approved")
      throw new ApiError(409, `Brief must be Approved before marking sent`);

    const updated = await updateBrief(id, {
      status: "Sent",
      finalizedAt: new Date().toISOString(),
    });

    res.json(updated);
  } catch (err) {
    handleError(err, res);
  }
});

router.post("/briefs/:id/discard", async (req, res): Promise<void> => {
  try {
    const { id } = req.params;
    const brief = await getBrief(id);
    if (!brief) throw new ApiError(404, "Brief not found");
    if (brief.status === "Discarded")
      throw new ApiError(409, "Brief is already discarded");

    if (brief.status === "Draft" && brief.docId) {
      try {
        const { ReplitConnectors } = await import("@replit/connectors-sdk");
        const connectors = new ReplitConnectors();
        await connectors.proxy(
          "google-drive",
          `/drive/v3/files/${brief.docId}`,
          { method: "DELETE" },
        );
      } catch (delErr) {
        logger.warn({ delErr, briefId: id }, "Could not delete brief doc from Drive — marking discarded anyway");
      }
    }

    const updated = await updateBrief(id, { status: "Discarded" });
    res.json(updated);
  } catch (err) {
    handleError(err, res);
  }
});

export default router;
