/**
 * Intelligence Payload Formatter
 *
 * Converts raw alert data into a strict Markdown document
 * that is both human-readable and parseable back into Notion blocks.
 */

// ── Helpers ───────────────────────────────────────────────────────────────────

function deriveFailureVector(whyStopped: string | null, headline: string): string {
  const src = (whyStopped ?? headline ?? "").toLowerCase();
  if (src.includes("ctep") || src.includes("drug supply") || src.includes("supplied drug")) return "DRUG SUPPLY HALTED";
  if (src.includes("futility") || src.includes("efficacy")) return "FUTILITY — EFFICACY FAILED";
  if (src.includes("safety") || src.includes("adverse") || src.includes("toxicity")) return "SAFETY SIGNAL FORCED STOP";
  if (src.includes("enrollment") || src.includes("recruit")) return "ENROLLMENT COLLAPSE";
  if (src.includes("covid") || src.includes("pandemic")) return "EXTERNAL FORCE MAJEURE";
  if (src.includes("company") || src.includes("sponsor") || src.includes("decision") || src.includes("prematurely")) return "SPONSOR WITHDRAWAL";
  return "SPONSOR DECISION";
}

function deriveZetaTier(severity: string): string {
  if (severity === "critical") return "CONFIRMED";
  if (severity === "high") return "PROBABLE";
  if (severity === "medium") return "INSUFFICIENT";
  return "UNSCORED";
}

function deriveDirective(module: string): string {
  if (module === "TerminationDetector")
    return "Debrief PI immediately. Evaluate whether this termination creates a positioning gap or enrollment opportunity for ONCO-247. Pull the patient population criteria and map against our current recruitment targets.";
  if (module === "ResultsIntelligence")
    return "Pull primary and secondary outcome data from the registry. Benchmark efficacy and AE profiles against ONCO-247's current endpoint specifications. Prepare a delta analysis before the next sponsor call.";
  if (module === "ToxicityCamouflage")
    return "Extract AE grade distribution. Identify whether the competitor's safety profile creates a differentiation advantage for ONCO-247. Flag any overlapping toxicity signals that may require our own protocol amendment.";
  if (module === "EnrollmentBleed")
    return "Track enrollment velocity across shared site networks. If bleed is accelerating, initiate site activation review and assess feasibility of accelerating ONCO-247 recruitment.";
  return "Review the full signal chain before the next PI sync. Assess strategic and operational implications for ONCO-247.";
}

// ── Types ─────────────────────────────────────────────────────────────────────

export interface AlertInput {
  nctId: string;
  module: string;
  severity: string;
  headline: string;
  detail: string;
  detectedAt: string;
}

export interface TrialMeta {
  studyTitle: string;
  sponsor: string;
  status: string;
  whyStopped: string | null;
  primaryCompletion: string;
  phase: string;
}

export interface FormattedPayload {
  drugName: string;
  nctId: string;
  vector: string;
  zetaTier: string;
  directive: string;
  markdown: string;
}

// ── Main formatter ────────────────────────────────────────────────────────────

export function formatIntelligencePayload(
  alert: AlertInput,
  meta: TrialMeta,
  pmids: string[] = [],
): FormattedPayload {
  const drugName = meta.studyTitle
    ? meta.studyTitle.split(" ").slice(0, 5).join(" ")
    : alert.nctId;

  const vector = meta.status === "TERMINATED"
    ? deriveFailureVector(meta.whyStopped, alert.headline)
    : deriveFailureVector(null, alert.headline);

  const zetaTier = deriveZetaTier(alert.severity);
  const directive = deriveDirective(alert.module);

  const detectedTs = new Date(alert.detectedAt).toLocaleString("en-US", {
    month: "short", day: "numeric", year: "numeric",
    hour: "2-digit", minute: "2-digit",
  });

  const pmidLines = pmids.length > 0
    ? pmids.map(pmid => `- https://pubmed.ncbi.nlm.nih.gov/${pmid}/`).join("\n")
    : "- No linked publications available at this time.";

  const smokingGun = meta.status === "TERMINATED" && meta.whyStopped
    ? `\n## Termination Record\n\n> "${meta.whyStopped}"\n`
    : "";

  const markdown = `# 🚨 COMPETITOR THREAT: ${drugName} (${alert.nctId})

**Sponsor:** ${meta.sponsor}  
**Phase:** ${meta.phase}  
**Status:** ${meta.status}  
**Primary Completion:** ${meta.primaryCompletion}  
**Detected:** ${detectedTs}  
**Signal Module:** ${alert.module}  
**Severity:** ${alert.severity.toUpperCase()}

---

## Verdict: ${zetaTier}

> ${directive}

---

## The Mechanical Exploit: ${vector}

${alert.headline}

${alert.detail}
${smokingGun}
---

## Literature Support:

${pmidLines}

---

*Generated by Clinical Trials Co-Pilot — Signal Engine v2 — ONCO-247*`;

  return { drugName, nctId: alert.nctId, vector, zetaTier, directive, markdown };
}
